#!/usr/bin/env node
import { exec } from 'node:child_process';

exec('tesseract', function (error, stdout, stderr) {
  if (
    (error && error.toString().indexOf('tesseract') > -1) ||
    (stderr && stderr.toString().indexOf('tesseract') > -1)
  ) {
    console.log('Found tesseract, textract should be able to use it.');
  } else {
    console.log(
      'tesseract cannot be found/executed by this script, errors to follow.',
    );
    console.log('**************ERROR*****************');
    console.log(error);
    console.log('**************stderr*****************');
    console.log(stderr);
    console.log('**************stdout*****************');
    console.log(stdout);
  }
});
